// <auto-generated />
namespace Explore.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RenameidtoId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameidtoId));
        
        string IMigrationMetadata.Id
        {
            get { return "201305310520140_RenameidtoId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
